services:
  - type: web
    name: gearted-discord-bot
    env: python
    plan: starter
    buildCommand: pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GUILD_ID
        value: "1381740173234274364"
      - key: PORT
        value: "10000"
      - key: PYTHON_VERSION
        value: "3.10.12"
    autoDeploy: true
    healthCheckPath: /health
    disk:
      name: gearted-data
      size: 1
      mount: /opt/render/project/data
